# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: swift
xcode_workspace: Example/ACSegmentView.xcworkspace
xcode_sdk: iphonesimulator
xcode_scheme: ACSegmentView-Example
# cache: cocoapods
# podfile: Example/Podfile
before_install:
# - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
# - pod install --project-directory=Example

script:
- pod lib lint --allow-warnings
